### ISSUE TITLE
Task: Rencontres du 24 janvier

### ISSUE THREAD

**Issue by sjinko** [CUPUM/urb3519#5]
# Task Description
Rencontre sur Zoom: https://umontreal.zoom.us/j/9042301021?pwd=QUl4a2UzTTlDRGdFUTI0UXpVWEZoZz09

# List of actions
## Order of day
* Informations générale
* Mise à jour des calendriers
* Revue des projets (5 min. par personne)
    * Agathe
    * Jémérémie
    * Matthieu
    * Martin
    * Sabrina
* Prochaine rencontre

## To do
- [x] Action: Mise à jour du calendrier
- [x] Action: Planifier les rencontres à venir
- [x] Action: Discuter de l’avancement de chaque personne

**Comment by sjinko** [comment]
# Informations générale

# Mise à jour des calendriers


# Revue des projets (5 min. par personne)
## Agathe

## Jérémie

## Matthieu

## Martin

## Sabrina

# Prochaine rencontre
